### ISSUE TITLE
User Story: As a Site Owner. I want to be able to add dogs to the site ( 4 Story Points ) 

### ISSUE THREAD

**Issue by stevewhitehouse66** [stevewhitehouse66/Woofers#3]
As the Site Owner. I want to be able to add dogs to the site so that potential adopters can find them.

Actions
- [x] Add dog profile
- [x] Edit dog profile
- [x] Delete dog profile
- [x] Publish dog profile
